### Currently the version is fixed to 1.1
version: 1.1

notifiers:
### Custom API server
# Send an HTTP POST form to <api_url>,
# which contains "title", "body" and "url".
##
- type: custom
  api_url: "http://localhost:8080/"

### Telegram bot
# Authencate a telegram bot with <api_key>
# to send messages to <chats>.
##
- type: tgbot
  api_key: "123456:foobar"
  chats:
    - "114514"
    - "-1919810"

### Work Wechat app
# See https://hguandl.com/posts/weibo-watcher-deploy/
##
- type: workwx
  corpid: "wx20190501"
  agentid: "1000002"
  corpsecret: "rhodesisland"
  touser: "@all"

### iOS Bark
# Official API server: https://api.day.app
##
- type: bark
  tokens:
    - "qwertyuiop"
    - "asdfghjkl"

### IFTTT Webhook
# See https://maker.ifttt.com/use/demo-page
# (use your API key to replace "demo-page" above)
##
- type: ifttt
  webhooks:
    - event: "call"
      api_key: "amiya"
    - event: "sleep"
      api_key: "doctor"

watchers:
### Weibo with UID
# - type: weibo
#   # debug_url: "http://localhost:8088/weibo"
#   uid: 6279793937  # @明日方舟Arknights

- type: weibo
  uid: 7510240935  # debug

### Arknights game announcements
# - type: akanno
#   # debug_url: "http://localhost:8088/akanno"
#   channel: IOS  # Currently only iOS is supported.
