### Currently the version is fixed to 1.1
version: 1.1

watchers:
## Weibo with UID
- type: weibo
  # debug_url: "http://localhost:8088/weibo"
  uid: 6279793937  # @明日方舟Arknights

### Arknights game announcements
- type: akanno
  # debug_url: "http://localhost:8088/akanno"
  channel: IOS  # Currently only iOS is supported.
